name: CI
on: [push, pull_request]
jobs:
  build:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.9', '3.10', '3.11', '3.12', '3.13']
        myst-parser-version: [ '>=0.18.0,<1', '>=1,<2', '>=2,<3', '>=3,<4', '>=4,<5' ]
        exclude:
          # myst-parser 4 dropped support for Python 3.9
          - python-version: '3.9'
            myst-parser-version: '>=4,<5'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - run: pip install .[test,docs]
      - run: pip install "myst-parser${{ matrix.myst-parser-version }}"
      # Run pytest
      - run: pytest -vv tests
      # Also try building the docs in the docs directory
      - run: cd docs && sphinx-build -b dirhtml  . _build/dirhtml
        # but only in latest version, as earlier versions of myst-parser require earlier
        # versions of Sphinx and that causes problems building our docs
        if: ${{ matrix.myst-parser-version == '>=4,<5' }}
