name: CI
on: [push, pull_request]
jobs:
  build:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Need to use an older Ubuntu so Python 3.6 is available
        os: [macos-latest, windows-latest, ubuntu-20.04]
        python-version: [ '3.7', '3.8', '3.9', '3.10']
        myst-parser-version: [ '<0.18.0', '>=0.18.0' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - run: pip install .[test]
      - run: pip install "myst-parser${{ matrix.myst-parser-version }}"
      # Run pytest
      - run: pytest -vv --cov sphinxcontrib
      # Also try building the docs in the docs directory
      - run: pip install sphinx_rtd_theme
      - run: cd docs && make dirhtml
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: coveralls --service=github
