name: Lint
on: [push, pull_request]

jobs:
  lint:
    # Need to use an older Ubuntu so Python 3.6 is available
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
        architecture: x64
        cache: pip
    - run: pip install .[test]
    - run: flake8 .
    - run: isort .
